// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	ID              string  `json:"id"`
	Title           string  `json:"title"`
	Author          string  `json:"author"`
	Isbn            int     `json:"isbn"`
	AvailableCopies int     `json:"availableCopies"`
	IsBorrowed      bool    `json:"isBorrowed"`
	BorrowedBy      *User   `json:"borrowedBy,omitempty"`
	BorrowedAt      *string `json:"borrowedAt,omitempty"`
	CreatedA        string  `json:"createdA"`
	ReturnedAt      *string `json:"returnedAt,omitempty"`
	DueDate         *string `json:"dueDate,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NewBook struct {
	Title           string `json:"title"`
	Author          string `json:"author"`
	Isbn            int    `json:"isbn"`
	AvailableCopies int    `json:"availableCopies"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Query struct {
}

type SignupInput struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Username string `json:"username"`
	Token    string `json:"token"`
	Password string `json:"password"`
}
